/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProductDAO;

/**
 *
 * @author petja122
 */
public class MainMenu extends javax.swing.JFrame {

        private final ProductDAO dao;
        
	
	public MainMenu(ProductDAO dao) {
		initComponents();
                this.dao = dao;
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonAddProduct = new javax.swing.JButton();
      buttonViewProduct = new javax.swing.JButton();
      buttonExit = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      buttonAddProduct.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
      buttonAddProduct.setText("Add a New Product");
      buttonAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
      buttonAddProduct.setName("buttonAddProduct"); // NOI18N
      buttonAddProduct.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonAddProductActionPerformed(evt);
         }
      });

      buttonViewProduct.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
      buttonViewProduct.setText("View Products");
      buttonViewProduct.setName("buttonViewProduct"); // NOI18N
      buttonViewProduct.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonViewProductActionPerformed(evt);
         }
      });

      buttonExit.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
      buttonExit.setText("Exit");
      buttonExit.setName("buttonExit"); // NOI18N
      buttonExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonExitActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Product Administration");
      jLabel1.setName("jLabel1"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(buttonAddProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(buttonViewProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
               .addComponent(buttonExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(12, 12, 12)
            .addComponent(buttonAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(buttonViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGap(45, 45, 45))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void buttonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProductActionPerformed
      // create the dialog instance
		// the first parameter the parent window, and the second is the modal status
		ProductEditor productEditorDialog = new ProductEditor(this, true, this.dao);

		// centre the dialog on the parent window
		productEditorDialog.setLocationRelativeTo(this);

		// make the dialog visible
		productEditorDialog.setVisible(true);
   }//GEN-LAST:event_buttonAddProductActionPerformed

   private void buttonViewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewProductActionPerformed
      // create the dialog instance
		// the first parameter the parent window, and the second is the modal status
		ProductViewer productViewerDialog = new ProductViewer(this, true, this.dao);

		// centre the dialog on the parent window
		productViewerDialog.setLocationRelativeTo(this);

		// make the dialog visible
		productViewerDialog.setVisible(true);
   }//GEN-LAST:event_buttonViewProductActionPerformed

   private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
      System.exit(0);
   }//GEN-LAST:event_buttonExitActionPerformed

	/**
	 * @param args the command line arguments
	 
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog 
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				MainMenu mainMenuDialog = new MainMenu();
				mainMenuDialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				mainMenuDialog.setVisible(true);
			}
		});

		
	}*/

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton buttonAddProduct;
   private javax.swing.JButton buttonExit;
   private javax.swing.JButton buttonViewProduct;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables
}
