/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import dao.DAOException;
import java.math.BigDecimal;
import domain.Product;
import dao.ProductCollectionsDAO;
import dao.ProductDAO;
import dao.ProductJdbcDAO;
import helpers.SimpleListModel;
import java.awt.Window;
import java.util.Collection;
import javax.swing.JOptionPane;
import net.sf.oval.ConstraintViolation;
import net.sf.oval.Validator;
import net.sf.oval.exception.ConstraintsViolatedException;

/**
 *
 * @author petja122
 */
public class ProductEditor extends javax.swing.JDialog {

	//private ProductCollectionsDAO dao = new ProductCollectionsDAO();
	private final ProductDAO dao;
        private Product product;
	
	/**
	 * Creates new form ProductEditor
	 */
	public ProductEditor(Window parent, boolean modal, ProductDAO dao) {
		super(parent);
                super.setModal(modal);
		initComponents();
		
                this.dao = dao;
                
		comboboxCategory.setEditable(true);
                
		SimpleListModel productModel = new SimpleListModel();
		Collection<String> categories = dao.getCategories();
		productModel.updateItems(categories);
		comboboxCategory.setModel(productModel);
                
	}
        
        public ProductEditor(Window parent, boolean modal, Product productEditing, ProductDAO dao ) {
            this(parent, modal, dao);
            
            
            this.product = productEditing;
            this.setName("productDialog");
            
            txtID.setText(productEditing.getProductID());
            txtID.setEditable(false);
            
            txtName.setText(productEditing.getName());
            txtDescription.setText(productEditing.getDescription());
            comboboxCategory.setSelectedItem(productEditing.getCategory());
            txtPrice.setText(String.valueOf(productEditing.getPrice()));
            txtStock.setText(String.valueOf(productEditing.getStock()));
        }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      txtID = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      txtName = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtDescription = new javax.swing.JTextArea();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      txtPrice = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      txtStock = new javax.swing.JTextField();
      buttonSave = new javax.swing.JButton();
      buttonCancel = new javax.swing.JButton();
      comboboxCategory = new javax.swing.JComboBox<>();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Product Editor");
      jLabel1.setName("jLabel1"); // NOI18N

      jLabel2.setText("ID:");
      jLabel2.setName("jLabel2"); // NOI18N

      txtID.setName("txtID"); // NOI18N
      txtID.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtIDActionPerformed(evt);
         }
      });

      jLabel3.setText("Name:");
      jLabel3.setName("jLabel3"); // NOI18N

      txtName.setName("txtName"); // NOI18N

      jLabel4.setText("Description:");
      jLabel4.setName("jLabel4"); // NOI18N

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      txtDescription.setColumns(20);
      txtDescription.setRows(5);
      txtDescription.setName("txtDescription"); // NOI18N
      jScrollPane1.setViewportView(txtDescription);

      jLabel5.setText("Category:");
      jLabel5.setName("jLabel5"); // NOI18N

      jLabel6.setText("Price:");
      jLabel6.setName("jLabel6"); // NOI18N

      txtPrice.setName("txtPrice"); // NOI18N

      jLabel7.setText("Quantity in Stock:");
      jLabel7.setName("jLabel7"); // NOI18N

      txtStock.setName("txtStock"); // NOI18N

      buttonSave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      buttonSave.setText("Save");
      buttonSave.setName("buttonSave"); // NOI18N
      buttonSave.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonSaveActionPerformed(evt);
         }
      });

      buttonCancel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      buttonCancel.setText("Cancel");
      buttonCancel.setName("buttonCancel"); // NOI18N
      buttonCancel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonCancelActionPerformed(evt);
         }
      });

      comboboxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      comboboxCategory.setName("comboboxCategory"); // NOI18N
      comboboxCategory.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboboxCategoryActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(6, 6, 6)
                  .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel2)
                           .addComponent(jLabel3)
                           .addComponent(jLabel4)))
                     .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtID)
                     .addComponent(txtName)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                     .addComponent(comboboxCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(txtPrice)
                     .addComponent(txtStock))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2)
               .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel4)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(comboboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
               .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtIDActionPerformed

   private void comboboxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxCategoryActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_comboboxCategoryActionPerformed

   private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
       try {
		String id = txtID.getText();
		String name = txtName.getText();
		String description = txtDescription.getText();
		String category = (String) comboboxCategory.getSelectedItem();
		BigDecimal price = new BigDecimal(txtPrice.getText());
		BigDecimal stock = new BigDecimal(txtStock.getText());			  

		//System.out.println(id + name + description + category + price + stock);

		Product product = new Product();
		product.setProductID(id);
		product.setName(name);
		product.setDescription(description);
		product.setCategory(category);
		product.setPrice(price);
		product.setStock(stock);

                new Validator().assertValid(product);
		dao.saveProduct(product);
		dispose();

		//System.out.println(product);
       } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, 
                                              "You have entered a price or quantity that is not a valid number.", 
                                              "Input Error", 
                                              JOptionPane.ERROR_MESSAGE);
        } catch (ConstraintsViolatedException ex) {
            // get the violated constraints from the exception
            ConstraintViolation[] violations = ex.getConstraintViolations();

            // create a nice error message for the user
            String msg = "Please fix the following input problems:";
            for (ConstraintViolation cv : violations) {
               msg += "\n  - " + cv.getMessage();
            }

            // display the message to the user
            JOptionPane.showMessageDialog(this, msg, "Input Error", JOptionPane.ERROR_MESSAGE);
         } catch(DAOException ex){
             // create a nice error message for the user
            String msg = "Please fix the following input problems:";
            msg += "\n  - " + ex.getMessage();

            // display the message to the user
            JOptionPane.showMessageDialog(this, msg, "Input Error", JOptionPane.ERROR_MESSAGE);
         }          
   }//GEN-LAST:event_buttonSaveActionPerformed

   private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
      dispose();
   }//GEN-LAST:event_buttonCancelActionPerformed

	/**
	 * @param args the command line arguments
	 
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProductEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProductEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProductEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProductEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog 
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ProductEditor dialog = new ProductEditor(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}*/

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton buttonCancel;
   private javax.swing.JButton buttonSave;
   private javax.swing.JComboBox<String> comboboxCategory;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea txtDescription;
   private javax.swing.JTextField txtID;
   private javax.swing.JTextField txtName;
   private javax.swing.JTextField txtPrice;
   private javax.swing.JTextField txtStock;
   // End of variables declaration//GEN-END:variables
}
